server:
  port: 8081
  address: 0.0.0.0
  servlet:
    context-path: /api/wisdom

spring:
  application:
    name: wisdom
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://
    username:
    password:
  redis:
    host:
    database: 0
    port: 6379
    password:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  page-size-zero: true
  params: countSql


wisdom:
  jwt:
    header: Authorization
    expire: 604800 #7天，秒单位
    secret: ji8n3439n439n43ld9ne9343fdfer49h

aliyun:
  oss:
    endpoint:
    accessKeyId:
    accessKeySecret:
    bucketName:

management:
  security:
    enabled : false